Autocommit por GitHub: alterações: add 'bash/.bash_functions' add 'bash/.bashrc' add 'home/.local/bin/gphotos' add 'home/.local/bin/sf-inertia' add 'home/.xprofile' add 'vscode/.config/Code/User/settings.json' remove 'vscode/.config/Code/User/snippets/favicon.code-snippets' add 'vscode/.config/Code/User/snippets/html.json' remove 'vscode/.config/Code/User/snippets/ogp.code-snippets' add 'vscode/.config/Code/User/snippets/shellscript.json' add 'zsh/.zsh_aliases' add 'zsh/.zsh_functions' add 'zsh/.zshrc' add 'home/.local/bin/inertia-old.sh' add 'home/.local/bin/sf-icecastkh-liquidsoap' add 'home/bin/nginx_clear_cache.sh' add 'nginx/etc/nginx/snippets/api.conf' add 'nginx/etc/nginx/snippets/api.old.conf' add 'nginx/etc/nginx/snippets/arquivo' add 'nginx/etc/nginx/snippets/deny.conf' add 'nginx/etc/nginx/snippets/drupal.conf' add 'nginx/etc/nginx/snippets/errors-sdm.conf' add 'nginx/etc/nginx/snippets/errors.conf' add 'nginx/etc/nginx/snippets/expires.conf' add 'nginx/etc/nginx/snippets/expires.map' add 'nginx/etc/nginx/snippets/fastcgi-php.conf' add 'nginx/etc/nginx/snippets/laravel.conf' add 'nginx/etc/nginx/snippets/map.codes' add 'nginx/etc/nginx/snippets/mvc.conf' add 'nginx/etc/nginx/snippets/php-alias.conf' add 'nginx/etc/nginx/snippets/php.conf' add 'nginx/etc/nginx/snippets/snakeoil.conf' add 'nginx/etc/nginx/snippets/static.conf' add 'nginx/etc/nginx/snippets/vue-php.conf' add 'nginx/etc/nginx/snippets/vue.conf'
Signed-off-by: Lucas Saliés Brum <lucas@archlinux.com.br>

diff --git a/home/.local/bin/gphotos b/home/.local/bin/gphotos
--- a/home/.local/bin/gphotos
+++ b/home/.local/bin/gphotos
@@ -6,10 +6,16 @@
 # Feito por Lucas Saliés Brum, a.k.a. sistematico <lucas@archlinux.com.br>
 #
 # Criado em:        16/06/2021 08:28:30
-# Última alteração: 16/06/2021 08:28:33
+# Última alteração: 03/02/2022 05:27:42
+
+if ! command -v rclone &> /dev/null
+then
+    echo "rclone could not be found"
+    exit
+fi
 
 dir="$HOME/google/photos"
-bw="--bwlimit 900k" # b|k|M|G
+bw="--bwlimit 2M" # b|k|M|G
 
 if [ $1 ]; then
 	/usr/bin/find $dir -type f | /usr/bin/wc -l
@@ -18,4 +24,3 @@ else
     	/usr/bin/rclone copy gphotos: $dir $bw 2>&1
 	fi
 fi
-
