Criado o branch 'old'

diff --git a/home/.local/bin/screencast b/home/.local/bin/screencast
--- a/home/.local/bin/screencast
+++ b/home/.local/bin/screencast
@@ -9,80 +9,90 @@
 # Criado em: 09/06/2017 23:26:41
 # Última Atualização: 31/10/2018 12:35:15
 
-list_descendants () {
-  local children=$(ps -o pid= --ppid "$1")
+apps=("ffmpeg" "xrandr" "pacmd")
 
-  for pid in $children
-  do
-    list_descendants "$pid"
-  done
-
-  echo "$children "
-}
-
-
-# ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow,placebo
-PRESET="ultrafast"
-EXT="mp4"
-DATA=$(date +%H-%M-%S)
-ICONE="${HOME}/.local/share/icons/Newaita/devices/48/camera-video.svg"
-RESOLUCAO=$(xrandr | grep '*' | awk 'NR==1{print $1}')
-DISTRO="arch"
-
-APPS=("ffmpeg" "xrandr" "pacmd")
-for APP in ${APPS[@]}
+for app in ${apps[@]}
 do
-    command -v $APP >/dev/null 2>&1 || { echo >&2 "O aplicativo $APP não está instalado. Abortando."; exit 1; }
+    command -v $app >/dev/null 2>&1 || { echo >&2 "O aplicativo $app não está instalado. Abortando."; exit 1; }
 done
 
-notifycommand="$HOME/bin/notify.sh VideoDown ${ICONE}"
-#notifycommand="notify-send -h int:transient:1 -i $ICONE"
+preset="veryfast" # ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow,placebo
+[ -f ${HOME}/.config/polybar/config ] && cor=$(awk -F# '/secondary/{print $2;exit}' ${HOME}/.config/polybar/config) || cor="bf616a"
+lixeira="${HOME}/.local/share/Trash"
+icone="${HOME}/.local/share/icons/elementary/video-display.png"
+
+resolucao=$(xrandr | grep '*' | awk 'NR==1{print $1}')
+audio=$(pacmd list-sinks | grep -A 1 'index: 0' | awk 'NR==2{print $2}' | awk '{print substr($0,2,length($0)-2)}') # list-sources, list-sinks
 
 if [ -f ~/.config/user-dirs.dirs ]; then
-    . ~/.config/user-dirs.dirs
-    CAMINHO="${XDG_VIDEOS_DIR}/screencast"
+    source ~/.config/user-dirs.dirs
+    caminho="${XDG_VIDEOS_DIR}/screencast/"
 else
-    CAMINHO="${HOME}/video/screencast"
+    caminho="${HOME}/video/screencast/"
 fi
 
-CAMINHO="${CAMINHO}/$(date +%Y)/$(date +%m)/$(date +%d)"
-ARQUIVO="screencast-${DATA}.${EXT}"
+if [ ! $1 ]; then
+    data=$(date +%Y-%m-%d_%H-%M-%S)
+    arquivo="${caminho}/screencast-${data}.mp4"
+    [ ! -d $caminho ] && mkdir -p $caminho
+fi
 
-[ ! -d $CAMINHO ] && mkdir -p $CAMINHO
-
-#if pgrep -x "ffmpeg" > /dev/null;
-if pgrep -x "ffmpeg" > /dev/null && test -f "/tmp/videodown.pid" && test -f "/tmp/screencast.step1.${EXT}";
+if pgrep -x "ffmpeg" > /dev/null
 then
-    [ -f /tmp/screencast.step2.${EXT} ] && rm -f /tmp/screencast.step2.${EXT}
-    [ -f /tmp/screencast.final.${EXT} ] && rm -f /tmp/screencast.final.${EXT}
-
-    NEWPID=$(/bin/cat /tmp/videodown.pid)
-
-    $notifycommand "ScreenCast" "Gravação terminada, matando os processos: $(list_descendants $NEWPID)"
-    kill -QUIT $(list_descendants $NEWPID)
-    #kill -TERM $NEWPID
-    sleep 2
-   
-    $notifycommand "ScreenCast" "Conversão para o WhatsApp"
-    ffmpeg -i /tmp/screencast.step1.${EXT} -c:v libx264 -profile:v baseline -level 3.0 -pix_fmt yuv420p /tmp/screencast.step2.${EXT}
-    
-    $notifycommand "ScreenCast" "Corte de 5 segundos no começo e 3 no final"
-
-    dur=$(ffprobe -i /tmp/screencast.step2.${EXT} -show_entries format=duration -v quiet -of csv="p=0")
-    trim=$((dur - 3))
-
-    ffmpeg -ss 2 -t $trim -i /tmp/screencast.step2.${EXT} /tmp/screencast.final.${EXT}
-
-    mv /tmp/screencast.final.${EXT} "${CAMINHO}/${ARQUIVO}"
-
-    $notifycommand "ScreenCast" "ScreenCast salvo ${ARQUIVO}" 
-    rm -f /tmp/videodown.pid /tmp/screencast.step1.${EXT} /tmp/screencast.step2.${EXT}
+    [ "$(pgrep -x polybar)" ] && [ "$1" == "status" ] && echo "%{F#${cor}}%{F-}" && exit
+    if [ ! $1 ]; then
+        killall ffmpeg
+        #notify-send -i $icone "ScreenCast" "O vídeo <b>$arquivo</b> foi terminado."
+        notify-send -i $icone "ScreenCast" "Vídeo terminado."
+        exit 0
+    fi
 else
-    [ -f /tmp/screencast.step1.${EXT} ] && rm -f /tmp/screencast.step1.${EXT}
-    echo $$ > /tmp/videodown.pid
-    #$notifycommand "ScreenCast" "ScreenCast iniciado\n\nPID: $(/bin/cat /tmp/videodown.pid)"
-    $notifycommand "ScreenCast" "Gravação iniciada"
-    ffmpeg -async 1 -f x11grab -s $RESOLUCAO -i $DISPLAY -f pulse -ac 2 -i default -c:v libx264 -crf 23 -c:a aac -ac 2 -b:a 128k -movflags faststart /tmp/screencast.step1.${EXT}
+    [ "$(pgrep -x polybar)" ] && [ "$1" == "status" ] && echo "%{F#${cor}}%{F-}" && exit
+    if [ ! "$1" ]; then
+        #notify-send -i $icone "ScreenCast" "O vídeo <b>$arquivo</b> foi iniciado..."
+        notify-send -i $icone "ScreenCast" "Vídeo iniciado..."
+
+        #ffmpeg -f x11grab -r 25 -s $resolucao -i :0.0 -f pulse -i default -preset $preset -crf 0 -threads 0 -probesize 10M $arquivo
+        #ffmpeg -f x11grab -r 25 -s $resolucao -i :0.0 -f pulse -i default -preset $preset -c:v libx264 -c:a aac -b:a 128k -probesize 50M $arquivo
+        #ffmpeg -f x11grab -r 25 -s $resolucao -i :0.0 -f pulse -i default -preset $preset -c:v libx264 -c:a aac -b:a 128k -probesize 50M $arquivo
+        #ffmpeg -thread_queue_size 512 -f x11grab -r 30 -s $resolucao -i :0.0 -f pulse -i default -preset $preset -c:v libx264 -c:a aac -b:a 128k $arquivo -probesize 50M
+        #ffmpeg -thread_queue_size 512 -f x11grab -r 30 -s $resolucao -i :0.0 -f pulse -ac 2 -i default -preset $preset -c:v libx264 -c:a aac -b:a 128k $arquivo -probesize 50M
+        #ffmpeg -thread_queue_size 512 -f x11grab -r 30 -s $resolucao -i :0.0 -f pulse -ac 2 -i default -preset $preset -c:v h264_nvenc -qp 0 -c:a aac -b:a 128k $arquivo -probesize 50M
+        #ffmpeg -f alsa -i pulse -f x11grab -r 25 -s $resolucao -i :0 -c:a aac -c:v libx264 -threads 0 $arquivo -probesize 50M
+        #ffmpeg -f x11grab -r 25 -s $resolucao -i :0 -f pulse -ac 2 -i default -preset $preset -c:v libx264 -c:a aac -b:a 128k $arquivo -probesize 50M
+        #ffmpeg -f x11grab -r 25 -s $resolucao -i :0 -f pulse -ac 2 -i default -preset $preset -c:v libx264 -c:a aac -b:a 128k $arquivo
+        #ffmpeg -y -i screencast-2018-01-15_06-09-22.mp4 -c:v mpeg4 -b:v 600k -c:a libmp3lame output.avi
+        #ffmpeg -y -f x11grab -r 25 -s $resolucao -i :0 -f pulse -ac 2 -i default -preset $preset -c:v mpeg4 -b:v 800k -c:a libmp3lame $arquivo
+        #ffmpeg -y -f x11grab -s $resolucao -i :0 -f pulse -ac 2 -i default -preset $preset -c:v libx264 -c:a libmp3lame $arquivo
+        #ffmpeg -f x11grab -s $resolucao -i :0 -f pulse -ac 2 -i default -preset $preset -c:v libx264 -pix_fmt yuv444p -c:a libmp3lame $arquivo
+        #ffmpeg -f x11grab -s $resolucao -i :0 -f pulse -ac 2 -i default -preset $preset -c:v mpeg4 -c:a libmp3lame $arquivo
+
+        #ffmpeg -f x11grab -s $resolucao -i :0 -c:v libx264 -crf 23 -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -ac 2 -strict experimental -b:a 128k -movflags faststart $arquivo
+
+        ffmpeg -async 1 -f x11grab -s $resolucao -i :0 -f pulse -ac 2 -i default -c:v libx264 -crf 23 -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -ac 2 -strict experimental -b:a 128k -movflags faststart $arquivo
+
+    elif [ "$1" == "clear" ]; then
+        icone="${HOME}/.local/share/icons/elementary/user-trash.png"
+        #listagem=(${caminho}* 2> /dev/null)
+        #if [ ${#listagem[@]} -gt 0 ]; then
+        if ls ${caminho}* 2> /dev/null; then
+            mv ${caminho}* ${lixeira}/files/
+            export DISPLAY=:0 ; canberra-gtk-play -i trash-empty 2>&1
+            dbus-launch notify-send -i $icone "ScreenCast" "Pasta de screencasts limpa!"
+        else
+            export DISPLAY=:0 ; canberra-gtk-play -i trash-empty 2>&1
+            dbus-launch notify-send -i $icone "ScreenCast" "Pasta de screencasts já está limpa!"
+        fi
+        exit 0
+    fi
 fi
+
+#if [ -f $arquivo ]; then
+#    xclip -selection c -t 'video/mp4' -i $arquivo
+#    exit 0
+#fi
+
+# Re-encode
+# #ffmpeg -y -i screencast-2018-01-15_06-09-22.mp4 -c:v mpeg4 -b:v 600k -c:a libmp3lame output.avi
 
 exit 0
